### ISSUE TITLE
Could not find a part of the path 'C:\Documents'

### ISSUE THREAD

**Issue by SteveSitekitcare** [Gekidoku/BetterFireBaseNotificationsPlugin#2]
I pulled the latest code and changed the csproj file content back to dotnet 7 as it was on dotnet 8.

I attempt to buld the package with no other changes and receive  

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find a part of the path 'C:\Documents'.	Plugin.BetterFirebasePushNotification	C:\Program Files\dotnet\sdk\7.0.403\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets	221	
```

Am I missing something?

All my other MAUI apps works fine

**Comment by TomSproet** [comment]
No clue where that is comming from. 
In the middle of updating the package for ios since this version is using some older firebase libraries that still contain bitcode
ill look into this as well

**Comment by TomSproet** [comment]
Can you try to remove the Readme from the .csproj?  <ItemGroup>
```
  <None Include="..\..\..\..\Documents\LICENSE.txt">
    <Pack>True</Pack>
    <PackagePath>\</PackagePath>
  </None>
</ItemGroup>

<ItemGroup>
  <None Update="LICENSE.txt">
    <Pack>True</Pack>
    <PackagePath>\</PackagePath>
  </None>
</ItemGroup>  

```
remove all this

**Comment by SteveSitekitcare** [comment]
> Can you try to remove the Readme from the .csproj?
> 
> ```
>   <None Include="..\..\..\..\Documents\LICENSE.txt">
>     <Pack>True</Pack>
>     <PackagePath>\</PackagePath>
>   </None>
> </ItemGroup>
> 
> <ItemGroup>
>   <None Update="LICENSE.txt">
>     <Pack>True</Pack>
>     <PackagePath>\</PackagePath>
>   </None>
> </ItemGroup>  
> ```
> 
> remove all this

I removed that and this 

`<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>`

and it now builds
